# Site settings
title: Neil Moore's page
email: neil@cfconline.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Insane ramblings of a lunatic.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.bigoh.co.uk" # the base hostname & protocol for your site
twitter_username: neilmoore67
github_username:  neil-ca-moore

# Build settings
markdown: kramdown
